[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "vrije-KnD-final-project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
