[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "vrije-KnD-final-project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.1.2,<3"
pandas = ">=2.2.3,<3"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.9.2,<4"
sparqlwrapper = ">=2.0.0,<3"
