[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "vrije-KnD-final-project"
platforms = ["osx-arm64","win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
numpy = ">=2.1.2,<3"
pandas = ">=2.2.3,<3"
jupyter = ">=1.1.1,<2"
matplotlib = ">=3.9.2,<4"
scipy = ">=1.14.1,<2"
sparqlwrapper = ">=2.0.0,<3"
rdflib = ">=7.0.0,<8"
networkx = ">=3.4.2,<4"
owlready2 = ">=0.47,<0.48"
scikit-learn = ">=1.5.2,<2"
plotly = ">=5.24.1,<6"

[pypi-dependencies]
onto-tool = "*"
